name: core
description: Common shared code for club angel.
version: 0.0.1
#homepage: https://www.example.com
#author: succorer <email@example.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.11.1+7
  cloud_firestore: ^0.12.5+2
  firebase_storage: ^3.0.2
  flutter_image_compress: ^0.6.0
  libphonenumber: ^1.0.0
  shared_preferences: ^0.5.3+1
  uuid: ^2.0.2
  equatable: ^0.2.0
  bloc: ^0.14.4
  flutter_bloc: ^0.20.1
  http: ^0.12.0+2

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  intl_translation: 0.17.0
