name: before_sunrise
description: Before Sunrise

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  core:
    path: ../core
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^3.0.0+1
  font_awesome_flutter: ^8.4.0
  country_code_picker: ^1.1.5
  multi_image_picker: ^4.5.2
  carousel_slider: ^1.3.0
  connectivity: ^0.4.3+2
  sliding_up_panel: ^0.3.4
  keyboard_avoider: ^0.1.2
  cached_network_image: ^1.1.1
  intl: ^0.15.8
  flutter_screenutil: ^0.5.3
  flutter_localizations:
    sdk: flutter
  flutter_xlider: ^2.5.2
  sprintf: "^4.0.0"
  modal_progress_hud: ^0.1.3
  progress_dialog: ^1.1.0+1
  flutter_bloc: ^0.20.1
  keyboard_visibility: ^0.5.6
  timeago: ^2.0.18
  url_launcher: ^3.0.0
  flutter_map: ^0.5.0
  latlong: ^0.6.1
  flutter_rating_bar: ^2.0.0+2
  network_image_to_byte: ^0.0.1
  image: ^2.1.4
  share_extend: ^1.0.9
  scroll_to_index: ^1.0.2
  clipboard_manager: ^0.0.4
  grouped_list: ^1.2.1
  # webview_flutter -> Info.plist -> io.flutter.embedded_views_preview -> YES
  # webview_flutter -> App Transport Security Settings -> YES
  webview_flutter: ^0.3.14+1
  keyboard_actions: ^2.1.2
  flutter_time_picker_spinner: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

# flutter create --org com.pfxstudio -i swift -a kotlin --description 'Before Sunrise' before_sunrise

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

    - assets/loader/
    - assets/avatars/
    - assets/files/

    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    - assets/localizables/en.json
    - assets/localizables/kr.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: QuickSand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf

    - family: SpoqaHanSansRegular
      fonts:
        - asset: assets/fonts/SpoqaHanSansBold.ttf
        - asset: assets/fonts/SpoqaHanSansLight.ttf
        - asset: assets/fonts/SpoqaHanSansRegular.ttf
        - asset: assets/fonts/SpoqaHanSansThin.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
